import { Bell } from "lucide-react";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

import { AppSidebar } from "@/components/app-sidebar";
import { Button } from "@/components/ui/button";
import { NotificationBadge } from "@/components/ui/notification-badge";
import { Separator } from "@/components/ui/separator";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";

import { DeviceUnavailable } from "@/components/device-unavailable";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

{
  /* <NotificationBadge
  label='42'
  //className='bg-blue-500 translate-x-2.5 -translate-y-2.5'
>
  <Button
    type='button'
    variant='outline'
  >
    <Mail className='h-4 w-4' />
  </Button>
</NotificationBadge> */
}

// or:

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <SidebarInset>
            <header className="flex h-16 shrink-0 items-center gap-2 border-b px-4">
              <SidebarTrigger className="-ml-1" />
              <Separator
                orientation="vertical"
                className="mr-2 data-[orientation=vertical]:h-4"
              />
              <NotificationBadge
                className="ml-auto"
                label="12"
                variant="destructive"
              >
                <Link href={"/notifications"}>
                  <Button type="button" variant="ghost">
                    <Bell />
                  </Button>
                </Link>
              </NotificationBadge>
            </header>
            <DeviceUnavailable />
            <div className="sm:hidden flex flex-col items-center justify-center h-screen p-2">
              {children}
            </div>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
